GET_PRODUCTS_QUERY = 'SELECT product_ID, name, price, in_stock FROM products'
GET_COURIER_QUERY = 'SELECT courier_ID, name, phone FROM couriers'
SELECT_PRODUCTS_MATCHING_ID_QUERY = 'SELECT product_id, COUNT(*) FROM products WHERE product_id = %s'
GET_ORDER_QUERY = 'SELECT orders.order_id, customers.customer_name, customers.customer_address, customers.customer_phone, couriers.name as courier, orders.status, SUM(order_products.quantity) AS items FROM orders LEFT JOIN customers ON orders.customer_id = customers.customer_id LEFT JOIN couriers ON orders.courier_id = couriers.courier_id LEFT JOIN order_products ON orders.order_id = order_products.order_id GROUP by orders.order_id;'
GET_CUSTOMERID_FOR_ORDER_QUERY = 'SELECT customer_id FROM orders WHERE order_id = %s'
GET_ORDER_PRODUCTS_QUERY = 'SELECT order_products.product_id, products.name, order_products.quantity FROM order_products LEFT JOIN products ON order_products.product_id = products.product_id WHERE order_id = %s;'